version: '3.9'
services:
  mysql-kc:
    image: mysql:latest
    ports:
      - 3377:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: keycloak_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  mysql-service:
    image: mysql:latest
    ports:
      - 3379:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Quiz
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - Quiz-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: quay.io/keycloak/keycloak:23.0.7
    command: start-dev
    ports:
      - 8081:8080
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:mysql://mysql-kc:3306/keycloak_db
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      #      PROXY_ADDRESS_FORWARDING: 'true' // deploying on vps server
      #      KC_PROXY: edge // deploying on vps server
      KC_HOSTNAME: localhost
    #      KC_HOSTNAME_STRICT_HTTPS: 'true' // deploying on vps server
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:
  Quiz-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:
    external: true
  Quiz-and-mysql-volume:
    external: true